publishDir = "docs"

baseURL = "https://ishtiaquezico.github.io/blog/"
canonifyURLs = True
languageCode = "en-US"
title = "পাইথনে পয়লা"


[params]
  description = "পাইথন দিয়া কী হবে তা পরের আলাপ"
  githubUsername = "IshtiaqueZico"
  twitterUsername = "iazico"
  tagline = "পাইথন বোঝার নোটখাতা"

  [[menu.main]]
      name = "O nas"
      weight = -110
      identifier = "about"
      url = "/about/"
